### ISSUE TITLE
processrefuned.exe has stopped working

### ISSUE THREAD

**Issue by morpimor** [Spajed/processrefund#2]
![image](https://user-images.githubusercontent.com/33716971/33939855-65f6a86c-e015-11e7-8457-7f859d3af716.png)

someone know what the problem ?

i used windows 7 X64

**Comment by Spajed** [comment]
Hi, you compiled it to 32bit, this is currently works in x64

**Comment by Spajed** [comment]
It looks like you compiled it to 32bits?
This currently works in x64 only

**Comment by hfiref0x** [comment]
On Windows 7 and below ReadFile/WriteFile lpNumberOfBytesRead/lpNumberOfBytesWritten are required input parameter despite declared as optional on MSDN, so they can't be NULL.

I actually did the same mistake as I completely forgot about this behavior and only build on Windows above 7.

**Comment by Spajed** [comment]
oops fixed https://github.com/Spajed/processrefund/commit/8b7cb98d1f7300393e185aefddcc26238c313393
